= Bajon-Consulting V1
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank

ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

// /!\ A MODIFIER !!!
:baseURL: https://github.com/summerflamme/Bajon-Consulting

toc::[]

## Membres du projet

|=== 
| Nom | Rôle 

| https://github.com/ClvSimon[Simon CLAVEL] | Scrum master et développeur  
| https://github.com/kwadjanib[Bilon KWADJANI] | Développeur  
| https://github.com/summerflamme[Robin GOURGUES] |  développeur  
| https://github.com/PierreCornu[Pierre CORNU] | Développeur 
| https://github.com/titouangauze[Titouan Gauze] | Développeur & base de donnée
|===




## Livrables attendus
**- Dossier de recueil et d’analyse des besoins : (lien)**  
Ce document détaillera les besoins fonctionnels et techniques de l’application, ainsi que les attentes du client (BAJON Consulting). Il décrira les fonctionnalités principales de l’application, les priorités, ainsi que les spécifications techniques pour le développement.


**- Maquettes et prototypes : (lien)**  
Des maquettes visuelles de l'interface utilisateur (UI) de l'application seront créées pour permettre au commanditaire de valider l'ergonomie et les fonctionnalités. Ces prototypes serviront également à guider le développement de la version initiale de l'application.


**- Application web déployée en version initiale (V1) : (lien)**  
La première version de l'application sera développée et déployée en ligne. Cette version fonctionnelle comprendra les principales fonctionnalités permettant de gérer les audits, de suivre les étapes et les livrables, ainsi que de centraliser les informations des clients. L’application sera responsive, accessible depuis différents supports (PC, tablette, mobile), et permettra de gérer l'offre « Essentiel ».


**- Documentation technique : (lien)**  
La documentation technique détaillera l’architecture du système, les technologies utilisées, les choix techniques faits durant le développement ainsi que les étapes de déploiement et de maintenance. Elle sera utile pour les futures évolutions du projet et pour l’intégration d’autres fonctionnalités.


**- Guide utilisateur : (lien)**  
Ce document aura pour but de guider les utilisateurs dans l’utilisation de l’application. Il expliquera le fonctionnement de l’application, la gestion des audits, le suivi des livrables et l’utilisation des différentes fonctionnalités. Ce guide sera à la fois simple et complet pour assurer une adoption rapide de l’outil par les équipes de BAJON Consulting.

##Guide d'installation



##Guide d'utilisation



##Roadmap
**Ce qui est prévu pour les versions futures :**
- Génération document word
- Génération de document pdf
- Nouveaux boutons disponibles dans les formulaires
- utilisation de versioning

