FROM maven:3.9.6-eclipse-temurin-21

# Crée un utilisateur non-root
RUN useradd -m -s /bin/bash vscode

# Configure Maven pour vscode
ENV MAVEN_CONFIG=/home/vscode/.m2
ENV PATH="/usr/share/maven/bin:${PATH}"

WORKDIR /workspace/Code/Back/Bajon_audit_App

COPY pom.xml ./
COPY .mvn/ .mvn

RUN mvn -B -DskipTests dependency:resolve || true

# Créer le répertoire target et donner les droits à vscode
RUN mkdir -p /workspace/Code/Back/Bajon_audit_App/target \
    && chown -R vscode:vscode /workspace/Code/Back/Bajon_audit_App/target

# Passer à l'utilisateur non-root
USER vscode

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]
