services:
  backend:
    build:
      context: ./Back/Bajon_audit_App
      dockerfile: Dockerfile
    container_name: bajon_backend_prod
    restart: always
    env_file: .env
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Front/Bajon_Consulting_Audit_App
      dockerfile: Dockerfile
      args:
        # Remplace <IP_PUBLIQUE> par l’IP du serveur
        VITE_API_URL: "http://localhost:8080"
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: bajon_frontend_prod
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
