version: '3.8'

services:
  backend:
    build:
      context: ./Back/Bajon_audit_App
      dockerfile: Dockerfile.dev
    container_name: bajon_backend_dev
    volumes:
      # Mount the Bajon-Consulting repository root as /workspace inside the container
      - ../:/workspace:cached
      # Ensure the repo .git is visible so commits inside the container affect the host repo
      - ../.git:/workspace/.git
      # Use a named volume for the backend target directory so the container can write build artifacts
      - backend_target:/workspace/Code/Back/Bajon_audit_App/target
    env_file: ../.env
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bajon_audit_db
      SPRING_DATASOURCE_USERNAME: bajon
      SPRING_DATASOURCE_PASSWORD: bajon
    depends_on:
      - db

  frontend:
    build:
      context: ./Front/Bajon_Consulting_Audit_App
      dockerfile: Dockerfile.dev
    container_name: bajon_frontend_dev
    volumes:
      # Mount the Bajon-Consulting repository root as /workspace
      - ../:/workspace:cached
      # Mount the parent repo's .git so the container uses Bajon-Consulting's git
      - ../.git:/workspace/.git
    env_file: ../.env
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: bajon_db_dev
    environment:
      POSTGRES_DB: bajon_audit_db
      POSTGRES_USER: bajon
      POSTGRES_PASSWORD: bajon
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  backend_target:
