spring.application.name=Bajon_audit_App
spring.profiles.default=dev

# Supabase configuration
#supabase.url=https://bajonconsulting.endide.com/
server.port=${SERVER_PORT:8080}

# Supabase configuration
supabase.url=${SUPABASE_URL}
supabase.anon-key=${SUPABASE_ANON_KEY}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}



# Database configuration (disable auto-configuration for now)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
