spring.application.name=Bajon_audit_App

# Configuration de la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://176.169.53.93:5432/postgres
spring.datasource.username=myuser.your-tenant-id
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1

# Configuration du serveur
server.port=8080
